language: php
php:
      - '7.1'
before_script:
      - composer install -vvv
      - wget https://github.com/swoole/swoole-src/archive/v4.0.0.tar.gz
      - tar -zxvf v4.0.0.tar.gz
      - cd swoole-src-4.0.0
      - phpize
      - ./configure
      - make -j 2
      - make install
      - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - cd ..
script: ./vendor/bin/phpunit tests